/**
 * @file addlevel.h
 * @brief Declaration of the addLevel class and its signals.
 */

#ifndef ADDLEVEL_H
#define ADDLEVEL_H

#include <QComboBox>
#include <QDialog>
#include "global_vars.h"

namespace Ui {
class addLevel;
}

/**
 * @class addLevel
 * @brief Dialog window for adding levels.
 *
 * This class provides a dialog window for adding levels. It includes functionality
 * to interact with a table widget to input level details and a combo box for selecting
 * level numbers.
 */
class addLevel : public QDialog
{
    Q_OBJECT

public:
    /**
 * @brief Constructor for the addLevel class.
 * @param parent The parent widget (optional).
 */
    explicit addLevel(QWidget *parent = nullptr);

    /**
 * @brief Destructor for the addLevel class.
 */
    ~addLevel();

private slots:
    /**
 * @brief Slot to handle click events on the Cancel button.
 *
 * Hides the dialog window when the Cancel button is clicked.
 */
    void on_pushButton_2_clicked();

    /**
 * @brief Slot to handle click events on the Add button.
 *
 * Retrieves data from the table widget, including text data and the selected
 * item from a combo box, emits a signal with the retrieved data, and closes
 * the dialog window.
 */
    void on_pushButton_clicked();

signals:
    /**
     * @brief Signal emitted to add the level data to the main window.
     * @param row The row of data to be added as a QStringList.
     */
    void addLevelMain(const QStringList &row);

    /**
     * @brief Signal emitted to update the main window after adding a level.
     */
    void updateMainWindow();

private:
    Ui::addLevel *ui; /**< User interface object pointer generated by Qt Designer. */
};

#endif // ADDLEVEL_H
